In [294]:
import pandas as pd

In [295]:
df=pd.read_excel('weather_dataset_stage1.xls')

In [296]:
df.head(30)

,weather_dataset,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,tableName,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Date\tVARCHAR(512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,temperature\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Average humidity (%\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Average dewpoint (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Average barometer (in\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Average windspeed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Average gustspeed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Average direction (°deg\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Rainfall for month (in\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rainfall for year (in\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Maximum rain per minute\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Maximum temperature (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Minimum temperature (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Maximum humidity (%\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Minimum humidity (%\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Maximum pressure\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Minimum pressure\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Maximum windspeed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Maximum gust speed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Maximum heat index (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Date1\tVARCHAR(512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Month\tINT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,diff_pressure\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
28,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
29,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'

In [297]:
col=df.iloc[27].to_numpy()
col

array(['Date', ' Temperature', ' Average humidity (%',
       ' Average dewpoint (°F', ' Average barometer (in',
       ' Average windspeed (mph', ' Average gustspeed (mph',
       ' Average direction (°deg', ' Rainfall for month (in',
       'Rainfall for year (in', ' Maximum rain per minute',
       ' Maximum temperature (°F', ' Minimum temperature (°F',
       ' Maximum humidity (%', ' Minimum humidity (%',
       ' Maximum pressure', ' Minimum pressure',
       ' Maximum windspeed (mph', ' Maximum gust speed (mph',
       ' Maximum heat index (°F', 'Date1', ' Month', ' diff_pressure'],
      dtype=object)

In [298]:
df.columns=col

In [299]:
df.head()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,tableName,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Date\tVARCHAR(512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,temperature\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Average humidity (%\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [300]:
df.drop(range(28),inplace=True)

In [301]:
df.reset_index(drop=True,inplace=True)

In [302]:
df.head()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05','23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0',...,'5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'

In [303]:
df['Date']=df['Date'].replace(regex="'",value="")

In [304]:
df.head()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02,'43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03,'25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04,'9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05,'23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0',...,'5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'

In [305]:
df['Date']=pd.to_datetime(df['Date'],format="%Y-%m-%d")

ValueError: time data 2022-02-29 doesn't match format specified

In [306]:
df[df['Date']=='2022-02-29']

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
2366,2022-02-29,'38.1','36.0','12.3','29.8','11.5','17.0','77.0','0.16','0.36',...,'73.0','22.0','30.023','29.702','29.9','39.1','45.9','2022-02-29','02','0.32099999999999795'
3751,2022-02-29,'37.6','31.0','8.7','29.8','8.0','11.6','236.0','0.48','0.49',...,'57.0','20.0','29.972','29.647','19.6','31.1','48.1','2022-02-29','02','0.32500000000000284'

In [307]:
df.drop([2366,3751],inplace=True)

In [308]:
df.reset_index(drop=True,inplace=True)

In [309]:
df['Date']=pd.to_datetime(df['Date'],format="%Y-%m-%d")

In [310]:
df

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02,'43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03,'25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04,'9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05,'23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0',...,'5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,2022-07-25,'62.8','60.0','48.1','29.7','2.5','4.0','242.0','0.33','4.47',...,'90.0','36.0','29.781','29.645','8.1','17.3','77.5','2022-07-25','07','0.13599999999999923'
3897,2022-07-26,'60.6','68.0','48.9','29.8','1.7','2.9','357.0','0.33','4.47',...,'90.0','40.0','29.93','29.745','11.5','15.0','77.5','2022-07-26','07','0.18499999999999872'
3898,2022-07-27,'61.7','64.0','47.4','29.9','2.2','4.0','66.0','0.33','4.47',...,'96.0','35.0','29.941','29.781','13.8','18.4','78.2','2022-07-27','07','0.16000000000000014'
3899,2022-07-28,'60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49',...,'94.0','35.0','29.792','29.675','17.3','26.5','77.6','2022-07-28','07','0.11700000000000088';
3900,2022-07-28,'60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49',...,'94.0','35.0','29.792','29.675','17.3','26.5','77.6','2022-07-28','07','0.11700000000000088';

In [311]:
df.duplicated().sum()

1

In [312]:
df.drop_duplicates(keep='first',inplace=True,ignore_index=True)

In [313]:
start=0
listYear=[]
check=df['Date'][0]
for k in range(1,len(df['Date'])):
    if df['Date'][k]>check:
        check=df['Date'][k]
    elif df['Date'][k]<check:
        end=k-1
        listYear.append([start,end])
        start=k
        check=df['Date'][k]
listYear.append([start,k])
listYear

[[0, 330],
 [331, 691],
 [692, 941],
 [942, 1278],
 [1279, 1598],
 [1599, 1955],
 [1956, 2306],
 [2307, 2671],
 [2672, 3007],
 [3008, 3331],
 [3332, 3690],
 [3691, 3899]]

In [314]:
year1=2023
for k in range(1,len(listYear)):
    for m in range(listYear[k][1]-listYear[k][0]+1):
        df.iloc[listYear[k][0]+m,0]=df.iloc[listYear[k][0]+m,0].replace(year=year1)
    year1+=1

In [316]:
df

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02,'43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03,'25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04,'9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05,'23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0',...,'5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,2033-07-24,'64.1','62.0','49.8','29.6','3.6','5.8','240.0','0.24','4.38',...,'86.0','35.0','29.686','29.577','15.0','25.3','77.4','2022-07-24','07','0.10899999999999821'
3896,2033-07-25,'62.8','60.0','48.1','29.7','2.5','4.0','242.0','0.33','4.47',...,'90.0','36.0','29.781','29.645','8.1','17.3','77.5','2022-07-25','07','0.13599999999999923'
3897,2033-07-26,'60.6','68.0','48.9','29.8','1.7','2.9','357.0','0.33','4.47',...,'90.0','40.0','29.93','29.745','11.5','15.0','77.5','2022-07-26','07','0.18499999999999872'
3898,2033-07-27,'61.7','64.0','47.4','29.9','2.2','4.0','66.0','0.33','4.47',...,'96.0','35.0','29.941','29.781','13.8','18.4','78.2','2022-07-27','07','0.16000000000000014'
3899,2033-07-28,'60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49',...,'94.0','35.0','29.792','29.675','17.3','26.5','77.6','2022-07-28','07','0.11700000000000088';

In [317]:
df.columns

Index(['Date', ' Temperature', ' Average humidity (%', ' Average dewpoint (°F',
       ' Average barometer (in', ' Average windspeed (mph',
       ' Average gustspeed (mph', ' Average direction (°deg',
       ' Rainfall for month (in', 'Rainfall for year (in',
       ' Maximum rain per minute', ' Maximum temperature (°F',
       ' Minimum temperature (°F', ' Maximum humidity (%',
       ' Minimum humidity (%', ' Maximum pressure', ' Minimum pressure',
       ' Maximum windspeed (mph', ' Maximum gust speed (mph',
       ' Maximum heat index (°F', 'Date1', ' Month', ' diff_pressure'],
      dtype='object')

In [321]:
df.drop('Date1',axis=1,inplace=True)

In [322]:
df

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'34.0','4.0','27.0','29.762','29.596','41.4','59.0','40.0','01','0.16600000000000037'
1,2022-01-02,'43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'37.0','4.0','16.0','29.669','29.268','35.7','51.0','52.0','01','0.4009999999999998'
2,2022-01-03,'25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'6.0','8.0','35.0','30.232','29.26','25.3','38.0','41.0','01','0.9719999999999978'
3,2022-01-04,'9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'-0.0','7.0','35.0','30.566','30.227','12.7','20.0','32.0','01','0.33899999999999864'
4,2022-01-05,'23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0',...,'15.0','5.0','13.0','30.233','29.568','38.0','53.0','32.0','01','0.6649999999999991'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,2033-07-24,'64.1','62.0','49.8','29.6','3.6','5.8','240.0','0.24','4.38',...,'55.3','86.0','35.0','29.686','29.577','15.0','25.3','77.4','07','0.10899999999999821'
3896,2033-07-25,'62.8','60.0','48.1','29.7','2.5','4.0','242.0','0.33','4.47',...,'55.1','90.0','36.0','29.781','29.645','8.1','17.3','77.5','07','0.13599999999999923'
3897,2033-07-26,'60.6','68.0','48.9','29.8','1.7','2.9','357.0','0.33','4.47',...,'50.5','90.0','40.0','29.93','29.745','11.5','15.0','77.5','07','0.18499999999999872'
3898,2033-07-27,'61.7','64.0','47.4','29.9','2.2','4.0','66.0','0.33','4.47',...,'43.6','96.0','35.0','29.941','29.781','13.8','18.4','78.2','07','0.16000000000000014'
3899,2033-07-28,'60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49',...,'46.0','94.0','35.0','29.792','29.675','17.3','26.5','77.6','07','0.11700000000000088';

In [323]:
df.columns

Index(['Date', ' Temperature', ' Average humidity (%', ' Average dewpoint (°F',
       ' Average barometer (in', ' Average windspeed (mph',
       ' Average gustspeed (mph', ' Average direction (°deg',
       ' Rainfall for month (in', 'Rainfall for year (in',
       ' Maximum rain per minute', ' Maximum temperature (°F',
       ' Minimum temperature (°F', ' Maximum humidity (%',
       ' Minimum humidity (%', ' Maximum pressure', ' Minimum pressure',
       ' Maximum windspeed (mph', ' Maximum gust speed (mph',
       ' Maximum heat index (°F', ' Month', ' diff_pressure'],
      dtype='object')

In [324]:
df.columns=['Date', 'Temperature', 'Average humidity (%)', 'Average dewpoint (°F)',
       'Average barometer (in)', 'Average windspeed (mph)',
       'Average gustspeed (mph)', 'Average direction (deg)',
       'Rainfall for month (in)', 'Rainfall for year (in)',
       'Maximum rain per minute', 'Maximum temperature (°F)',
       'Minimum temperature (°F)', 'Maximum humidity (%)',
       'Minimum humidity (%)', 'Maximum pressure', 'Minimum pressure',
       'Maximum windspeed (mph)', 'Maximum gust speed (mph)',
       'Maximum heat index (°F)', 'Month', 'diff_pressure']

In [375]:
pd.set_option('display.max_columns', None)
df.head()

,Date,Temperature,Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F),Month,diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,'01','0.16600000000000037'
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,'01','0.4009999999999998'
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0,'01','0.9719999999999978'
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,'01','0.33899999999999864'
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,'01','0.6649999999999991'

In [346]:
cols=df.columns
mothColIndex=cols.get_loc('Month')
mothColIndex

20

In [385]:
for k in range(1,mothColIndex):
    df.iloc[:,k]=df.iloc[:,k].replace(regex="'",value="")
    df.iloc[:,k]=df.iloc[:,k].astype(float)

In [387]:
df.head()

,Date,Temperature,Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F),Month,diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,01,0.16600000000000037
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,01,0.4009999999999998
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0,01,0.9719999999999978
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,01,0.33899999999999864
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,01,0.6649999999999991

In [388]:
k=mothColIndex
df.iloc[:,k]=df.iloc[:,k].replace(regex="'",value="")
df.iloc[:,k]=df.iloc[:,k].astype(int)

In [393]:
k=21
df.iloc[:,k]=df.iloc[:,k].replace(regex="'",value="")
df.iloc[:,k]=df.iloc[:,k].replace(regex=";",value="")
df.iloc[:,k]=df.iloc[:,k].astype(float)

In [394]:
df.head()

,Date,Temperature,Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F),Month,diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,1,0.166
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,1,0.401
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0,1,0.972
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,1,0.339
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,1,0.665

In [395]:
df.dtypes

Date                        datetime64[ns]
Temperature                        float64
Average humidity (%)               float64
Average dewpoint (°F)              float64
Average barometer (in)             float64
Average windspeed (mph)            float64
Average gustspeed (mph)            float64
Average direction (deg)            float64
Rainfall for month (in)            float64
Rainfall for year (in)             float64
Maximum rain per minute            float64
Maximum temperature (°F)           float64
Minimum temperature (°F)           float64
Maximum humidity (%)               float64
Minimum humidity (%)               float64
Maximum pressure                   float64
Minimum pressure                   float64
Maximum windspeed (mph)            float64
Maximum gust speed (mph)           float64
Maximum heat index (°F)            float64
Month                                int32
diff_pressure                      float64
dtype: object

In [ ]:
df.to_csv('weatherData.csv',index=False)